# Generated by Django 4.2 on 2023-04-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickit.cart'),
        ),
    ]
