# Generated by Django 4.2 on 2023-04-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0002_alter_cart_user'),
        ('tickit', '0002_alter_event_cart'),
    ]

    operations = [
    ]
