# Generated by Django 4.2 on 2023-04-03 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0003_merge_0002_alter_cart_user_0002_alter_event_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cart',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickit.user'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
