# Generated by Django 4.2 on 2023-04-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0004_remove_event_cart_event_user_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default='default_image_url', max_length=255),
        ),
    ]
